### ISSUE TITLE
哦?

### ISSUE THREAD

**Issue by AmagiSakuya** [hiyouga/Ice-chan#1]
冰酱是用冰河的素材训练的AI么

**Comment by hiyouga** [comment]
这个AI目前还没有经过微调，参数是[THUDM/ChatGLM-6B](https://github.com/THUDM/ChatGLM-6B)的原始版本，之后会考虑尝试微调这个模型来掌握更多领域内知识。

**Comment by AmagiSakuya** [comment]
人工冰河加入群聊

**Comment by villons946** [comment]
当尝试扫描QQ二维码的时候显示登录失败和“当前环境存在风险，为保障你的账号安全，暂时无法登录。”

**Comment by villons946** [comment]
AssertionError: Torch not compiled with CUDA enabled
我很抱歉没能完成部署。但是经过尝试新的QQbot确实能登录了，作者的更新是有效的。由于我一开始部署过b站秋叶的一键包，但我还是等待自动下载。可惜后来爆内存了（laptop3060 6GB，16GB）。后来我试图改web_chatglm中的参数改成本地的模型并且清理内存之后可以加载模型但是随后出现这个问题。已知我用秋叶up的一键包可以运行chatglm（但可能配置确实刚刚好压线能跑）参照pytorch的教程发现torch.cuda.is_available()的回显是false。但是本地已经搭建好cuda并且写好环境变量了，不知道如何解决了。
